darktheme finally written and "tested"

diff --git a/darktheme b/darktheme
--- a/darktheme
+++ b/darktheme
@@ -10,20 +10,10 @@
 
 
 CMD_NAME="darktheme"
-#TIMINGS="/home/${USER}/.local/share/settheme/timings"
-DARKTHEME_TIMER="/home/${USER}/.config/systemd/user/darktheme.timer"
-LIGHTTHEME_TIMER="/home/${USER}/.config/systemd/user/lighttheme.timer"
 
 
-# mkfile creates a file and all parent directories.
-mkfile() {
-
-	filename=$(basename $TIMINGS)
-	folder=${1%$filename}
-
-	mkdir -p "$folder"
-	touch "$1"
-}
+# Source global variables and functions
+source globals.sh
 
 
 # If no arguments are provided the theme is changed to breeze dark. TODO: move org.kde.breezedark.desktop into a variable inside a config file and make it editable using this command
@@ -33,29 +23,16 @@ mkfile() {
 [[ -n $1 && -n $2 ]] && {
 
 	# Check argument
-	[[ $1 == "set" ]] || { echo "invalid command: $1"; exit 0; }
+	[[ $1 == "set" ]] || { echo "Invalid command: $1"; exit 0; }
 
-	# Check good date format
-	[[ $2 =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]] || { echo "$2 is not a valid date format. Use instead HH:MM:SS"; exit 0; }
-
-	# Check if date is valid
-	[[ $2 =~ ^([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]$ ]] || { echo "Date not valid. It can range from 00:00:00 to 23:59:59"; exit 0; }
-
-	# Check if timings file exists. If not, create it.
-	[[ -e $TIMINGS ]] || mkfile $TIMINGS
-
-	# Convert date in HH:MM:SS format into seconds
-	time=$(date -d"$2" +%s)
+	L_TIME=$(get_time $LIGHTTHEME_TIMER)
 
 	# If inserted date is equal to lighttheme date, throw an error
-	[[ $time != $L_TIME ]] || { echo "darktheme activation time cannot be the same as lighttheme"; exit 0; }
+	[[ $2 != $L_TIME ]] || { echo "Dark theme activation time cannot be the same as lighttheme"; exit 0; }
 
-	# If D_TIME line is not present add it, otherwise
-	# replace the existing one with the new one.
-	[[ $(grep -E "D_TIME=[0-9]*" $TIMINGS) ]] && sed -i 's/D_TIME=[0-9]*/D_TIME=${time}/' $TIMINGS || echo "D_TIME=${time}" >> $TIMINGS
+	# Set light theme activation time
+	set_time $DARKTHEME_TIMER $2 || exit 1
 
-	# TODO: set time also for systemd units
-
-	echo "dark theme activation time successfully set to $2!"
-
+	echo "Dark theme activation time successfully set to $2!"
+	exit 0
 }
