enhanced set_time error checking and system units sinergy + formatting + commenting

diff --git a/lighttheme b/lighttheme
--- a/lighttheme
+++ b/lighttheme
@@ -49,26 +49,32 @@ get_time() {
 #
 set_time() {
 
-	# Argument check
+	# Argument check.
 	[[ -z $1 || -z $2 ]] && { echo "missing arguments"; return 1; }
 
 	# Check if file ($1) is either $DARKTHEME_TIMER or $LIGHTTHEME_TIMER.
 	[[ $1 == $DARKTHEME_TIMER || $1 == $LIGHTTHEME_TIMER ]] || { 
-		echo "theme activation time can be retrieved only by either $LIGHTTHEME_TIMER or $DARKTHEME_TIMER"; 
+		echo "Theme activation time can be retrieved only by either $LIGHTTHEME_TIMER or $DARKTHEME_TIMER"; 
 		return 1;
 	}
 	
 	# Check if file ($1) exists. If not settheme is not installed.
 	[[ -e $1 ]] || { echo "$1 doesn't exist. You might have to run install.sh."; return 1; }
 
-	# Check good date format
+	# Check good date format.
 	[[ $2 =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]] || { echo "$2 is not a valid date format. Use instead HH:MM:SS"; return 1; }
 
-	# Check if date is valid
+	# Check if date is valid.
 	[[ $2 =~ ^([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]$ ]] || { echo "Date not valid. It can range from 00:00:00 to 23:59:59"; return 1; }
 
-	# Replace time in .timer file
-	sed -iE 's/^OnCalendar=\*-\*-\* ([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]$/OnCalendar=*-*-* 15:00:00/' $1
+	# Replace time in .timer file.
+	sed -Ei "s/^OnCalendar=\*-\*-\* ([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]\$/OnCalendar=*-*-* $2/" $1 || { echo Cannot change light theme activation time; return 1; }
+
+	# Get current theme activation time.
+	local current_time=$(sed -nE '/^OnCalendar=\*-\*-\* ([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]$/p' $1 | grep -oE "[0-9]{2}:[0-9]{2}:[0-9]{2}")
+
+	# If activation time has not changed, throw an error.
+	[[ $current_time != $2 ]] && { echo Cannot change light theme activation time; return 1; }
 
 	return 0
 }
@@ -81,16 +87,16 @@ set_time() {
 [[ -n $1 && -n $2 ]] && {
 
 	# Check argument
-	[[ $1 == "set" ]] || { echo "invalid command: $1"; exit 0; }
+	[[ $1 == "set" ]] || { echo "Invalid command: $1"; exit 0; }
 
 	D_TIME=$(get_time $DARKTHEME_TIMER)
 
 	# If inserted date is equal to darktheme date, throw an error
-	[[ $2 != $D_TIME ]] || { echo "lighttheme activation time cannot be the same as darktheme"; exit 0; }
+	[[ $2 != $D_TIME ]] || { echo "Light theme activation time cannot be the same as darktheme"; exit 0; }
 
 	# Set light theme activation time
-	[[ $(set_time $LIGHTTHEME_TIMER $2) ]] || exit 1
+	set_time $LIGHTTHEME_TIMER $2 || exit 1
 
-	echo "light theme activation time successfully set to $2!"
+	echo "Light theme activation time successfully set to $2!"
 	exit 0
 }
