refactoring

diff --git a/lighttheme b/lighttheme
--- a/lighttheme
+++ b/lighttheme
@@ -9,21 +9,97 @@
 #
 
 
-TIMINGS="/home/${USER}/.local/share/settheme/timings"
+CMD_NAME="lighttheme"
+DARKTHEME_TIMER="/home/${USER}/.config/systemd/user/darktheme.timer"
+LIGHTTHEME_TIMER="/home/${USER}/.config/systemd/user/lighttheme.timer"
 
 
-# mkfile creates a file and all parent directories.
+#
+#	Create a file and all parent directories.
+#
+#	SYNTAX:		mkfile PATH
+#
 mkfile() {
 
-	filename=$(basename $TIMINGS)
-	folder=${1%$filename}
+	# Argument check
+	[[ -z $1 ]] && { echo "$(basename $0): missing arguments"; return 1; }
+	
+	local filename=$(basename $TIMINGS)
+	local folder=${1%$filename}
 
 	mkdir -p "$folder"
+
+	local ret_value=$?
+	[[ $ret_value != 0 ]] && return $ret_value
+
 	touch "$1"
+	
+	ret_value=$?
+	[[ $ret_value != 0 ]] && return $ret_value
+
+	return 0
 }
 
 
-# If no arguments are provided the theme is changed to breeze light.
+#
+#	Get theme activation time.
+#
+#	SYNTAX:		get_time PATH_TO_TIMER
+#
+get_time() {
+
+	# Argument check
+	[[ -z $1 ]] && { echo "missing arguments"; return 1; }
+
+	# Check if file ($1) is either $DARKTHEME_TIMER or $LIGHTTHEME_TIMER.
+	[[ $1 == $DARKTHEME_TIMER || $1 == $LIGHTTHEME_TIMER ]] || { 
+		echo "theme activation time can be retrieved only by either $LIGHTTHEME_TIMER or $DARKTHEME_TIMER"; 
+		return 1;
+	}
+
+	# Check if file ($1) exists. If not settheme is not installed.
+	[[ -e $1 ]] || { echo "$1 doesn't exist. You might have to run install.sh."; return 1; }
+
+	# Dark theme activation time
+	D_TIME=$(sed -n '/OnCalendar/p' $1 | \
+			 grep -oE "([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]")
+
+	return 0
+}
+
+#
+#	Set theme activation time.
+#
+#	SYNTAX:		set_time PATH_TO_TIMER TIME
+#
+set_time() {
+
+	# Argument check
+	[[ -z $1 || -z $2 ]] && { echo "missing arguments"; return 1; }
+
+	# Check if file ($1) is either $DARKTHEME_TIMER or $LIGHTTHEME_TIMER.
+	[[ $1 == $DARKTHEME_TIMER || $1 == $LIGHTTHEME_TIMER ]] || { 
+		echo "theme activation time can be retrieved only by either $LIGHTTHEME_TIMER or $DARKTHEME_TIMER"; 
+		return 1;
+	}
+	
+	# Check if file ($1) exists. If not settheme is not installed.
+	[[ -e $1 ]] || { echo "$1 doesn't exist. You might have to run install.sh."; return 1; }
+
+	# Check good date format
+	[[ $2 =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]] || { echo "$2 is not a valid date format. Use instead HH:MM:SS"; return 1; }
+
+	# Check if date is valid
+	[[ $2 =~ ^([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]$ ]] || { echo "Date not valid. It can range from 00:00:00 to 23:59:59"; return 1; }
+
+	# Replace time in .timer file
+	sed -iE 's/^OnCalendar=\*-\*-\* ([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]$/OnCalendar=*-*-* 15:00:00/' $1
+
+	return 0
+}
+
+
+# If no arguments are provided the theme is changed to breeze light. TODO: move org.kde.breeze.desktop into a variable inside a config file and make it editable using this command
 [[ -z $1 ]] && { lookandfeeltool -a 'org.kde.breeze.desktop' &> /dev/null; exit 0; }
 
 # If argument set is provided, light theme activation time is set.
@@ -31,18 +107,6 @@ mkfile() {
 
 	# Check argument
 	[[ $1 == "set" ]] || { echo "invalid command: $1"; exit 0; }
-
-	# Check good date format
-	[[ $2 =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]] || { echo "$2 is not a valid date format. Use instead HH:MM:SS"; exit 0; }
-
-	# Check if date is valid
-	[[ $2 =~ ^([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]$ ]] || { echo "Date not valid. It can range from 00:00:00 to 23:59:59"; exit 0; }
-
-	# Check if timings file exists. If not, create it.
-	[[ -e $TIMINGS ]] || mkfile $TIMINGS
-
-	# Convert date in HH:MM:SS format into seconds
-	time=$(date -d"$2" +%s)
 
 	# If inserted date is equal to darktheme date, throw an error
 	[[ $time != $D_TIME ]] || { echo "lighttheme activation time cannot be the same as darktheme"; exit 0; }
