lighttheme finally finished and tested. Now it should work

diff --git a/lighttheme b/lighttheme
--- a/lighttheme
+++ b/lighttheme
@@ -1,44 +1,56 @@
 #!/bin/bash
 #
-# --------------- lighttheme ---------------
+#		--------------- lighttheme ---------------
 #
-# This script can be used both to manually
-# set kde desktop theme to breeze (light) or 
-# to specify the time when it will be set
-# automatically.
+#		This script can be used both to manually
+#		set kde desktop theme to breeze (light) or 
+#		to specify the time when it will be set
+#		automatically.
 #
+
 
 TIMINGS="/home/${USER}/.local/share/settheme/timings"
 
+
+# mkfile creates a file and all parent directories.
 mkfile() {
 
-	FILENAME=$(echo $1 | grep -oE "[a-zA-Z_\-\.]*$")
-	FOLDER=${1%$FILENAME}
+	filename=$(basename $TIMINGS)
+	folder=${1%$filename}
 
-	mkdir -p "$FOLDER"
+	mkdir -p "$folder"
 	touch "$1"
 }
 
-if [ -z "$1" ]; then
-	lookandfeeltool -a 'org.kde.breeze.desktop' &> /dev/null
-elif [ -n "$1" -a -n "$2" ]; then
+
+# If no arguments are provided the theme is changed to breeze light.
+[[ -z $1 ]] && { lookandfeeltool -a 'org.kde.breeze.desktop' &> /dev/null; exit 0; }
+
+# If argument set is provided, light theme activation time is set.
+if [[ -n $1 && -n $2 ]]; then
 
 	# Check argument
-	[[ $1 -ne set ]] && echo "invalid command: $1"; exit 0
+	[[ $1 == "set" ]] || { echo "invalid command: $1"; exit 0; }
 
 	# Check good date format
-	[[ $2 =~ "^[0-9]{2}:[0-9][2]:[0-9][2]$" ]] || echo "$2 is not a valid date format. Use instead HH:MM:SS"; exit 0
+	[[ $2 =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]] || { echo "$2 is not a valid date format. Use instead HH:MM:SS"; exit 0; }
+
+	# Check if date is valid
+	[[ $2 =~ ^([01][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]$ ]] || { echo "Date not valid. It can range from 00:00:00 to 23:59:59"; exit 0; }
 
 	# Check if timings file exists. If not, create it.
 	[[ -e $TIMINGS ]] || mkfile $TIMINGS
 
 	# Convert date in HH:MM:SS format into seconds
-	TIME=$(date -d"$2" +%s)
+	time=$(date -d"$2" +%s)
 
 	# If inserted date is equal to darktheme date, throw an error
-	[[ $TIME -ne $D_TIME ]] || echo "lighttheme activation time cannot be the same as darktheme"; exit 0
+	[[ $time != $D_TIME ]] || { echo "lighttheme activation time cannot be the same as darktheme"; exit 0; }
 
-	# else set L_TIME to the inserted date
-	sed -i 's/L_TIME=[0-9]*/L_TIME=${TIME}/g' $TIMINGS
+	# If L_TIME line is not present add it, otherwise
+	# replace the existing one with the new one.
+	[[ $(grep -E "L_TIME=[0-9]*" $TIMINGS) ]] && sed -i 's/L_TIME=[0-9]*/L_TIME=${time}/' $TIMINGS || echo "L_TIME=${time}" >> $TIMINGS
+
+	echo "light theme activation time successfully set to $2!"
 
 fi
